name: Terraform Destroy - Lambda

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
      TF_VAR_clients_table_name: "clientes"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name soat-cluster --region us-east-1

      - name: Get Load Balancer ID from Service DNS
        id: get-lb-id
        run: |
          FULL_HOST=$(kubectl get svc fastfood-api -o jsonpath="{.status.loadBalancer.ingress[0].hostname}")
          LB_ID=$(echo "$FULL_HOST" | cut -d'-' -f1)
          echo "Full DNS: $FULL_HOST"
          echo "Extracted ID: $LB_ID"
          echo "LB_ID=$LB_ID" >> $GITHUB_ENV

      - name: Zip Lambda
        working-directory: lambda/authenticator
        run: |
          zip -r ../../terraform/authenticator/lambda-authenticator.zip .

      - name: Zip Lambda
        working-directory: lambda/authorizer
        run: |
          zip -r ../../terraform/authenticator/lambda-authorizer.zip .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/authenticator
        run: terraform init

      - name: Terraform Destroy
        working-directory: terraform/authenticator
        run: terraform destroy -auto-approve
